# Generated by Django 3.0.2 on 2020-01-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChadCao', '0002_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.IntegerField(auto_created=1, primary_key=True, serialize=False),
        ),
    ]
